<?php

/**
 * Actions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    merrymall
 * @subpackage model
 * @author     Wronglink
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class Actions extends BaseActions
{
  public function getLogoUrl()
  {
    return sprintf('/uploads/company/%d/action_images/%d/', $this->getCompanyId(), $this->getId()).$this->getLogo();
  }
  
  public function getLogoPath()
  {
    return sprintf('%s/company/%d/action_images/%d', sfConfig::get('sf_upload_dir'), $this->getCompanyId(), $this->getId());
  }
  
  public function getCompanyName()
  {
    return $this->getCompany()->getUrl();
  }
}