<?php

/**
 * CompanyProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    merrymall
 * @subpackage model
 * @author     Wronglink
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class CompanyProfile extends BaseCompanyProfile
{
}
