<?php

/**
 * Company
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    merrymall
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class Company extends BaseCompany
{
  public function getShopwindow()
  {
    $sw = '';
    if ($this->hasShopwindow())
    $sw = '/uploads/company/' . $this->getId() . '/sw.jpg';
    elseif ($this->isOffice())
    $sw = '/uploads/floor/sw_default_office.jpg';
    elseif ($this->isStore())
    $sw = '/uploads/floor/sw_default_store.jpg';
    return $sw;
  }

  public function getShopwindowPath()
  {
    return sfConfig::get('sf_upload_dir').'/company/' . $this->getId() . '/sw.jpg';
  }

  public function hasShopwindow()
  {
    return $this->getHasShopwindow();
  }

  public function getLogo()
  {
    $logo = '';
    if ($this->hasLogo())
    $logo = '/uploads/company/' . $this->getId() . '/logo.jpg';

    return $logo;
  }

  public function getLogoPath()
  {
    return sfConfig::get('sf_upload_dir').'/company/' . $this->getId() . '/logo.jpg';
  }

  public function hasLogo()
  {
    return $this->getHasLogo();
  }

  public function isStore()
  {
    return ($this->getType() == 'store');
  }

  public function isOffice()
  {
    return ($this->getType() == 'office');
  }

  public function getCartItems() {
    $q = Doctrine_Query::create()
    ->from('sCart s')
    ->where('s.company_id = ?', $this->getId());
    return Doctrine_Core::getTable('sCart')->getNotOrderedCartItems($q);
  }

  public function getCompanyName()
  {
    return $this->getUrl();
  }



}
