<?php

/**
 * mGameCart
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    merrymall
 * @subpackage model
 * @author     Manichev Alexander aka Astronom <a.manichev@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class mGameCart extends BasemGameCart
{
  /**
   * Добавляет новую позицию в корзину игрока
   * Реализация основного алгоритма игры
   *
   * @property Array $item_variant
   * @return Array
   */
  public function addCartItem($item_variant) {

    //    if($cart_item = Doctrine::getTable('sCart')->findCartItemByItemVariantIdWithUserNotOdered($item_variant['iv_id']))
    //    {
    //      $count = $cart_item->getCount() + $count;
    //      $cart_item->setCount($count);
    //      $cart_item->save();
    //
    //      return array('id' => $cart_item->id, 'count' => $count, 'exist' => true);
    //    }
    //    else {
    $accountId = sfContext::getInstance()->getUser()->getAttribute('game_account_id',null,'sfGuardSecurityUser');
    $account = mGameAccountTable::getInstance()->findOneById($accountId);

    $this->setItemVariantId($item_variant['iv_id']);
    $this->setCompanyId($item_variant['iv_company_id']);
    $this->setAccountId($accountId);
    $this->setPrice($item_variant['iv_price']);
    $this->setRound($account->getRound());
    $this->setCheckout('false');
    $this->save();

    return array('exist' => false,
      			   'id'  => $this->id,
    );
    //    }
  }

  /**
   * Оформляет текущую покупку
   */
  public function checkout()
  {
    $accountId = sfContext::getInstance()->getUser()->getAttribute('game_account_id',null,'sfGuardSecurityUser');
    $account = mGameAccountTable::getInstance()->findOneById($accountId);

    $account->proceedToCheckout($this->price);

    $this->setCheckout('true');

  }

  /**
   * Отменяет оформление покупки
   */
  public function unCheckout()
  {
    $this->setCheckout('false');
  }

}