<?php

/**
 * mGameUserItem
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    merrymall
 * @subpackage model
 * @author     Wronglink, Astronom <a.manichev@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class mGameUserItem extends BasemGameUserItem
{
  public function getVerification()
  {
    return $this->is_verified;
  }

}