<?php

/**
 * sCategory
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    merrymall
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class sCategory extends BasesCategory
{
//  public function getLevel()
//  {
//    return $this->level;
//  }

//  public function setLevel($level)
//  {
//    $this->level = $level;
//  }

  public function getTabbedName()
  {
    return $this->tabbedName;
  }

  public function setTabbedName($tabbedName)
  {
    $this->tabbedName = $tabbedName;
  }

  public function getParentId()
  {
    if (!$this->getNode()->isValidNode() || $this->getNode()->isRoot())
    {
      return null;
    }

    $parent = $this->getNode()->getParent();

    return $parent['id'];
  }

  public function getIndentedName()
  {
    return str_repeat('- ',$this['level']).$this['name'];
  }

  /**
   * Метод, возвращающий id всех потомков
   * @return NULL | array()
   */
  public function getChildrenIds()
  {
    if(!$this->getNode()->hasChildren())
    {
      return null;
    }

    foreach ($this->getNode()->getChildren() as $child)
    {
      $ids[] = $child->getId();
    }

    return $ids;
  }

  public function hasRoot()
  {
    return $this->getTree()->hasRoot() ? true: false;
  }
}
