<?php

/**
 * sCompanyOrderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sCompanyOrderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object sCompanyOrderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sCompanyOrder');
    }
}