<?php

/**
 * sCompanyOrder
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    merrymall
 * @subpackage model
 * @author     Alexander Manichev aka Astronom <a.manichev@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sCompanyOrder extends BasesCompanyOrder
{
  private $status = Array(
  	"preordered" => "Заказ принимается",
  	"ordered" => "Заказ принят",
  	"processed" => "Заказ отправлен",
  	"delivered" => "Заказ доставлен");

  public function getHumanStatus()
  {
    return $this->status[$this->getStatus()];
  }
}