<?php

/**
 * sItemVariant
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    merrymall
 * @subpackage model
 * @author     Wronglink
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class sItemVariant extends BasesItemVariant
{
  public function getUserSWishlist()
  {

  	$q = Doctrine_Query::create()
  	                  ->from('sWishlist')
  	                  ->where('user_id = 244')
  	                  ->andWhere('item_variant_id = ?', $this->getId());
    //return $q->fetchOne();
    return $this->getSWishlist()->get;
  }
}
