<?php

/**
 * sItem
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    merrymall
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class sItem extends BasesItem
{
  public function getImageUrl()
  {
    $url = '';

    if ($image = $this->getSImage())
    $url = $image->getImageUrl();
    else
    $url = '/images/c/item_default.jpg';

    return $url;
  }

  public function getThumbnailUrl($size)
  {
    $url = '';
    $images = $this->getSImages();
    if (sizeof($images))
    {
      $url = $images[0]->getThumbnailUrl($size);
    }
    else
    $url = '/images/c/item_default.jpg';

    return $url;
  }
  /**
   * Возвращает набор img tags с картинками товара
   *
   * @param integer $size Size of Image. 150px by Default
   */
  public function getImageGallery($size = 150)
  {
    //$gallery = '';
    $gallery = 'var itemImages = new Array(0';

    $images = $this->getSImages();
    if (sizeof($images))
    {
      foreach ($images as $image)
      {
        //$gallery .= image_tag($image->getThumbnailUrl($size));
        $gallery .= ',"'.$image->getThumbnailUrl($size).'"';
      }
     $gallery .= ');';
    }
    else $gallery = image_tag('/images/c/item_default.jpg');

    return $gallery;

  }

  public function getUrl()
  {
    return $this->getCompany()->getUrl();
  }

  public function getCompanyType()
  {
    return $this->getCompany()->getType();
  }
}