<?php

/**
 * sOfficeText
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    merrymall
 * @subpackage model
 * @author     Wronglink, Astronom <a.manichev@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sOfficeText extends BasesOfficeText
{
  public function getCompanyName()
  {
    return $this->getCompany()->getUrl();
  }

  public function getSlug()
  {
    return $this->getTitleSlug();
  }

  public function getType()
  {
    return $this->getCompany()->getType();
  }

}