<?php

/**
 * sOrder
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    merrymall
 * @subpackage model
 * @author     Wronglink
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class sOrder extends BasesOrder
{
  public function Ordered()
  {
   $this->setStatus('ordered');
   $this->save();
  }

  public function getSCompanyOrder($company_id)
  {
    $q = Doctrine::getTable('sCompanyOrder')
         ->createQuery('co')
         ->where('co.company_id = ?', $company_id)
         ->andWhere('co.order_id = ?', $this->id);

    return $q->fetchOne();
  }
}
