<?php

/**
 * sWishlist
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    merrymall
 * @subpackage model
 * @author     Wronglink
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
class sWishlist extends BasesWishlist
{
  public function getWishlistPreview() {

  }
// Метод реализующий добавление новой позиции в Wishlist
// Доработать!
  public function addWishlist($item_variant_id, $user_id) {

    $this->setUserId($user_id);
    $this->setItemVariantId($item_variant_id);
    $this->save();
  }

  public function moveToCart($s_wish, Doctrine_Connection $conn = null, $user_id, $item_variant_id)
  {
    $conn = $conn ? $conn : Doctrine::getTable('sCart')->getConnection();

    $cart = new sCart();

    $conn->beginTransaction();
    try
    {
      $cart->cartAdd($item_variant_id, $count = 1, $user_id);
      $s_wish->delete();
      $conn->commit();
    }
    catch(Doctrine_Exception $e)
    {
      $conn->rollBack();
      throw $e;
    }
  }

  public function findOneByUserId($user_id)
  {
    $q = Doctrine_Query::create()
                        ->where('user_id = ?', $user_id);
    return $q->execute();
  }
}
