<?php

/**
 * ymlCompany
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    merrymall
 * @subpackage model
 * @author     Wronglink, Astronom <a.manichev@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ymlCompany extends BaseymlCompany
{
  /**
   * Путь до директории каталогов
   * @var dir
   */
  protected $uploadDir;

  static $xmlTypes = array('application/xml', 'text/xml');

  /**
   * Возвращает путь до папки с файлвми
   * @return dir
   */
  public function getFilepath()
  {
    $this->uploadDir = sprintf('%s/company/%d/store_cataloge/', sfConfig::get('sf_upload_dir'), $this->getCompanyId());
    if(!is_dir($this->uploadDir))
    {
      try {
        mkdir($this->uploadDir);
      }
      catch (Exception $e)
      {
        echo $e->getMessage();
      }
    }

    return $this->uploadDir;

  }

  /**
   * Возвращает абсолютный путь к файлу
   * @return string
   */
  public function getAbsoluteFilePath()
  {
    return $this->getFilepath().$this->getFilename();
  }

  /**
   * Возвращает mime-type файла
   * @return Ambigous <string, NULL>
   */
  public function getFiletype()
  {
    return $this->guessFromFileinfo($this->getAbsoluteFilePath());
  }

  /**
   * Определяет является ли файл xml по mime-type
   * @return boolean
   */
  public function isXML()
  {
    $filetype = $this->getFiletype();

    foreach (self::$xmlTypes as $type)
    {
      if ($filetype == $type)
      {
        return true;
      }
    }

    return FALSE;
  }

  /**
   * Guess the file mime type with PECL Fileinfo extension
   *
   * @param  string $file  The absolute path of a file
   *
   * @return string The mime type of the file (null if not guessable)
   */
  protected function guessFromFileinfo($file)
  {
    if (!function_exists('finfo_open') || !is_readable($file))
    {
      return null;
    }

    if (!$finfo = new finfo(FILEINFO_MIME))
    {
      return null;
    }

    $type = $finfo->file($file);

    // remove charset (added as of PHP 5.3)
    if (false !== $pos = strpos($type, ';'))
    {
      $type = substr($type, 0, $pos);
    }

    return $type;
  }

}