# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  #sf_guard_plugin_success_signin_url: @homepage
  sf_guard_plugin_signin_form:  mmsfGuardFormSignin
  sf_guard_plugin_register_form: mmsfGuardFormRegister

  #Максимальное количество товаров на одной странице магазина
  max_items_on_store: 32
  
  #Анонимный покупатель
  anonymous_cookie_name:  merrymall_customer
  anonymous_cookie_expiration_age:  180
  
  #Game 
  #m_game_suggest_rules_form: mGameSuggestRulesForm
  
  #Максимальное число покупок в одном магазине за тур
  m_game_max_purchase_on_store_by_tour: 2
  m_game_max_accounts_on_brif_rating: 5
   