# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/05-Factories
prod:
  logger:
    class: sfAggregateLogger
    param:
      level: err
      loggers:
        sf_file_debug:
          class: sfFileLogger
          param:
            level: err
            file: %SF_LOG_DIR%/%SF_APP%_%SF_ENVIRONMENT%.log
            
  mailer:
    param:
      delivery_strategy: realtime
      transport:
        class:           Swift_SmtpTransport
        param:
          host:          smtp.gmail.com
          port:          465
          encryption:    ssl
          username:      support@merrymall.ru
          password:      QCLiO3i8EN

test:
  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions

  response:
    class: sfWebResponse
    param:
      send_http_headers: false

  mailer:
    param:
      delivery_strategy: none

dev:
  mailer:
    param:
      delivery_strategy: single_address
      delivery_address:  a.manichev@gmail.com
      transport:
        class:           Swift_SmtpTransport
        param:
          host:          smtp.gmail.com
          port:          465
          encryption:    ssl
          username:      support@merrymall.ru
          password:      QCLiO3i8EN

cache:
  storage:
    class: sfCacheSessionStorage
    param:
      session_name: merrymall_c
      session_cookie_path: / 
      session_cookie_domain: merrymall.ru
      session_cookie_lifetime: +30 days
      session_cookie_secure: false
      session_cookie_http_only: true
      cache: 
        class: sfAPCCache
        param: ~

all:
  routing:
    class: sfPatternRouting
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true

  view_cache_manager:
    class: sfViewCacheManager
    param:
      cache_key_use_vary_headers: true
      cache_key_use_host_name:    true
      
  storage:
    class: sfSessionStorage
    param:
      session_name: merrymall
      
  user:
    class: myUser
    param:
      timeout: 7200
      
