# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings
prod:
  .settings:
    no_script_name:         true
    cache:                  false
    logging_enabled:        true

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              true
    no_script_name:         false
    etag:                   false

cache:
  .settings:
    error_reporting: <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:       true
    cache:           true
    etag:            false

all:
  .actions:
    error_404_module:       error
    error_404_action:       error404
    
    module_disabled_module: error    # To be called when a user requests
    module_disabled_action: disabled # A module disabled in the module.yml
    
  .settings:
    default_culture:        ru_RU
    # Form security secret (CSRF protection)
    csrf_secret:            805c1475c668d5e441b6c65852906377b4526590
    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true
    
    #settings for JqueryPlugin
    jquery_path:            http://ajax.microsoft.com/ajax/jQuery/jquery-1.5.min.js
    
    standard_helpers:       [jQuery, Partial, Cache]

    enabled_modules:        [default, sfGuardAuth, sfGuardRegister, sfJqueryTreeDoctrineManager]

    login_module:           sfGuardAuth
    login_action:           signin

    secure_module:          sfGuardAuth
    secure_action:          secure
 
    check_lock:             true