generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sOfficeText
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          s_office_text
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:
        class: false
      form:
        class: BackendsOfficeTextForm
      edit:    ~
      new:     ~
