<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addmmcompanies extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('mm_companies', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 7,
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'url' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'unique' => true,
              'length' => 255,
             ),
             'type' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'office',
              1 => 'store',
              ),
              'notnull' => true,
              'length' => NULL,
             ),
             'has_logo' => 
             array(
              'type' => 'boolean',
              'notnull' => true,
              'default' => 0,
              'length' => 25,
             ),
             'has_shopwindow' => 
             array(
              'type' => 'boolean',
              'notnull' => true,
              'default' => 0,
              'length' => 25,
             ),
             'floor_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 6,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'position' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
              'url_idx' => 
              array(
              'fields' => 
              array(
               0 => 'url',
              ),
              ),
              'floor_id_idx' => 
              array(
              'fields' => 
              array(
               0 => 'floor_id',
              ),
              ),
              'sortable' => 
              array(
              'fields' => 
              array(
               0 => 'position',
               1 => 'floor_id',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('mm_companies');
    }
}