<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addmmfloors extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('mm_floors', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 6,
             ),
             'type' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'floor',
              1 => 'cornice',
              2 => 'tabloid',
              3 => 'roof',
              ),
              'notnull' => true,
              'length' => NULL,
             ),
             'text' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'class' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'has_companies' => 
             array(
              'type' => 'boolean',
              'default' => 0,
              'length' => 25,
             ),
             'url' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'position' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
              'url_idx' => 
              array(
              'fields' => 
              array(
               0 => 'url',
              ),
              ),
              'type_idx' => 
              array(
              'fields' => 
              array(
               0 => 'type',
              ),
              ),
              'sortable' => 
              array(
              'fields' => 
              array(
               0 => 'position',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('mm_floors');
    }
}