<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addmmactions extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('mm_actions', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 11,
             ),
             'title' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'text' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => NULL,
             ),
             'logo' => 
             array(
              'type' => 'string',
              'unique' => true,
              'length' => 255,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('mm_actions');
    }
}