<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addmmspropertiesvalues extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('mm_s_properties_values', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 11,
             ),
             'value' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'property_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 11,
             ),
             'item_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 11,
             ),
             'company_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 7,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
              'item_id_idx' => 
              array(
              'fields' => 
              array(
               0 => 'item_id',
              ),
              ),
              'company_id_idx' => 
              array(
              'fields' => 
              array(
               0 => 'company_id',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('mm_s_properties_values');
    }
}