<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addmmsorders extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('mm_s_orders', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 11,
             ),
             'delivery_price' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 8,
             ),
             'address' => 
             array(
              'type' => 'clob',
              'notnull' => true,
              'length' => NULL,
             ),
             'comment' => 
             array(
              'type' => 'clob',
              'length' => NULL,
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 11,
             ),
             'status' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'preordered',
              1 => 'ordered',
              2 => 'processed',
              3 => 'delivered',
              ),
              'default' => 'preordered',
              'notnull' => true,
              'length' => NULL,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('mm_s_orders');
    }
}