<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addfks extends Doctrine_Migration_Base
{
  public function up()
  {

    $this->createForeignKey('mm_s_cart', 'mm_s_cart_user_id_sf_guard_users_id', array(
             'name' => 'mm_s_cart_user_id_sf_guard_users_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_users',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
    ));
    $this->createForeignKey('mm_s_cart', 'mm_s_cart_item_variant_id_mm_s_item_variants_id', array(
             'name' => 'mm_s_cart_item_variant_id_mm_s_item_variants_id',
             'local' => 'item_variant_id',
             'foreign' => 'id',
             'foreignTable' => 'mm_s_item_variants',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
    ));
    $this->createForeignKey('mm_s_cart', 'mm_s_cart_company_id_mm_companies_id', array(
             'name' => 'mm_s_cart_company_id_mm_companies_id',
             'local' => 'company_id',
             'foreign' => 'id',
             'foreignTable' => 'mm_companies',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
    ));
    $this->createForeignKey('mm_s_cart', 'mm_s_cart_order_id_mm_s_orders_id', array(
             'name' => 'mm_s_cart_order_id_mm_s_orders_id',
             'local' => 'order_id',
             'foreign' => 'id',
             'foreignTable' => 'mm_s_orders',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
    ));



    $this->createForeignKey('mm_s_item_tag_map', 'mm_s_item_tag_map_tag_id_mm_s_tags_id', array(
             'name' => 'mm_s_item_tag_map_tag_id_mm_s_tags_id',
             'local' => 'tag_id',
             'foreign' => 'id',
             'foreignTable' => 'mm_s_tags',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
    ));

    $this->createForeignKey('mm_s_orders', 'mm_s_orders_user_id_sf_guard_users_id', array(
             'name' => 'mm_s_orders_user_id_sf_guard_users_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_users',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
    ));

    $this->createForeignKey('mm_s_item_tag_map', 'mm_s_item_tag_map_item_id_mm_s_items_id', array(
             'name' => 'mm_s_item_tag_map_item_id_mm_s_items_id',
             'local' => 'item_id',
             'foreign' => 'id',
             'foreignTable' => 'mm_s_items',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
    ));

    $this->createForeignKey('mm_s_tags', 'mm_s_tags_parent_id_mm_s_tags_id', array(
             'name' => 'mm_s_tags_parent_id_mm_s_tags_id',
             'local' => 'parent_id',
             'foreign' => 'id',
             'foreignTable' => 'mm_s_tags',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
    ));
    $this->createForeignKey('mm_s_wishlist', 'mm_s_wishlist_user_id_sf_guard_users_id', array(
             'name' => 'mm_s_wishlist_user_id_sf_guard_users_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_users',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
    ));
    $this->createForeignKey('mm_s_wishlist', 'mm_s_wishlist_item_variant_id_mm_s_item_variants_id', array(
             'name' => 'mm_s_wishlist_item_variant_id_mm_s_item_variants_id',
             'local' => 'item_variant_id',
             'foreign' => 'id',
             'foreignTable' => 'mm_s_item_variants',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
    ));
    $this->createForeignKey('sf_guard_group_permission_map', 'sf_guard_group_permission_map_group_id_sf_guard_groups_id', array(
             'name' => 'sf_guard_group_permission_map_group_id_sf_guard_groups_id',
             'local' => 'group_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_groups',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
    ));
    $this->createForeignKey('sf_guard_group_permission_map', 'spsi', array(
             'name' => 'spsi',
             'local' => 'permission_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_permissions',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
    ));
    $this->createForeignKey('sf_guard_remembered_keys', 'sf_guard_remembered_keys_user_id_sf_guard_users_id', array(
             'name' => 'sf_guard_remembered_keys_user_id_sf_guard_users_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_users',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
    ));
    $this->createForeignKey('sf_guard_users', 'sf_guard_users_company_id_mm_companies_id', array(
             'name' => 'sf_guard_users_company_id_mm_companies_id',
             'local' => 'company_id',
             'foreign' => 'id',
             'foreignTable' => 'mm_companies',
             'onUpdate' => NULL,
             'onDelete' => 'SET NULL',
    ));
    $this->createForeignKey('sf_guard_user_group_map', 'sf_guard_user_group_map_user_id_sf_guard_users_id', array(
             'name' => 'sf_guard_user_group_map_user_id_sf_guard_users_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_users',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
    ));
    $this->createForeignKey('sf_guard_user_group_map', 'sf_guard_user_group_map_group_id_sf_guard_groups_id', array(
             'name' => 'sf_guard_user_group_map_group_id_sf_guard_groups_id',
             'local' => 'group_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_groups',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
    ));
    $this->createForeignKey('sf_guard_user_permission_map', 'sf_guard_user_permission_map_user_id_sf_guard_users_id', array(
             'name' => 'sf_guard_user_permission_map_user_id_sf_guard_users_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_users',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
    ));
    $this->createForeignKey('sf_guard_user_permission_map', 'spsi_1', array(
             'name' => 'spsi_1',
             'local' => 'permission_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_permissions',
             'onUpdate' => NULL,
             'onDelete' => 'CASCADE',
    ));
    $this->createForeignKey('sf_guard_user_profiles', 'sf_guard_user_profiles_user_id_sf_guard_users_id', array(
             'name' => 'sf_guard_user_profiles_user_id_sf_guard_users_id',
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_users',
             'onUpdate' => NULL,
             'onDelete' => 'cascade',
    ));
  }

  public function down()
  {



    $this->dropForeignKey('mm_s_cart', 'mm_s_cart_user_id_sf_guard_users_id');
    $this->dropForeignKey('mm_s_cart', 'mm_s_cart_item_variant_id_mm_s_item_variants_id');
    $this->dropForeignKey('mm_s_cart', 'mm_s_cart_company_id_mm_companies_id');
    $this->dropForeignKey('mm_s_cart', 'mm_s_cart_order_id_mm_s_orders_id');

    $this->dropForeignKey('mm_s_item_tag_map', 'mm_s_item_tag_map_item_id_mm_s_items_id');
    $this->dropForeignKey('mm_s_item_tag_map', 'mm_s_item_tag_map_tag_id_mm_s_tags_id');
    $this->dropForeignKey('mm_s_orders', 'mm_s_orders_user_id_sf_guard_users_id');

    $this->dropForeignKey('mm_s_tags', 'mm_s_tags_parent_id_mm_s_tags_id');
    $this->dropForeignKey('mm_s_wishlist', 'mm_s_wishlist_user_id_sf_guard_users_id');
    $this->dropForeignKey('mm_s_wishlist', 'mm_s_wishlist_item_variant_id_mm_s_item_variants_id');
    $this->dropForeignKey('sf_guard_group_permission_map', 'sf_guard_group_permission_map_group_id_sf_guard_groups_id');
    $this->dropForeignKey('sf_guard_group_permission_map', 'spsi');
    $this->dropForeignKey('sf_guard_remembered_keys', 'sf_guard_remembered_keys_user_id_sf_guard_users_id');
    $this->dropForeignKey('sf_guard_users', 'sf_guard_users_company_id_mm_companies_id');
    $this->dropForeignKey('sf_guard_user_group_map', 'sf_guard_user_group_map_user_id_sf_guard_users_id');
    $this->dropForeignKey('sf_guard_user_group_map', 'sf_guard_user_group_map_group_id_sf_guard_groups_id');
    $this->dropForeignKey('sf_guard_user_permission_map', 'sf_guard_user_permission_map_user_id_sf_guard_users_id');
    $this->dropForeignKey('sf_guard_user_permission_map', 'spsi_1');
    $this->dropForeignKey('sf_guard_user_profiles', 'sf_guard_user_profiles_user_id_sf_guard_users_id');
  }
}