<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class addFKFile_Company extends Doctrine_Migration_Base
{
  public function up()
  {
    $this->createForeignKey('mm_s_file', 'mm_s_file_company_id_mm_companies_id', array(
             'name' => 'mm_s_file_company_id_mm_companies_id',
             'local' => 'company_id',
             'foreign' => 'id',
             'foreignTable' => 'mm_companies',
             'onUpdate' => '',
             'onDelete' => 'CASCADE',
    ));

    $this->addIndex('mm_s_file', 'mm_s_file_company_id', array(
             'fields' => 
    array(
    0 => 'company_id',
    ),
    ));

  }

  public function down()
  {
    $this->dropForeignKey('mm_s_file', 'mm_s_file_company_id_mm_companies_id');

    $this->removeIndex('mm_s_file', 'mm_s_file_company_id', array(
             'fields' => 
    array(
    0 => 'company_id',
    ),
    ));

  }
}