<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version40 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('mm_s_file', 'comment', 'clob', '', array(
             'AFTER' => 'filename'
             ));
    }

    public function down()
    {
        $this->removeColumn('mm_s_file', 'comment');
    }
}