<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version41 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('mm_s_companies_orders', array(
             'id' =>
             array(
              'type' => 'integer',
              'primary' => '1',
              'unsigned' => '1',
              'autoincrement' => '1',
              'length' => '4',
             ),
             'order_id' =>
             array(
              'type' => 'integer',
              'notnull' => '1',
              'unsigned' => '1',
              'length' => '4',
             ),
             'company_id' =>
             array(
              'type' => 'integer',
              'notnull' => '1',
              'unsigned' => '1',
              'length' => '3',
             ),
             'delivery_price' =>
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'status' =>
             array(
              'type' => 'enum',
              'values' =>
              array(
              0 => 'preordered',
              1 => 'ordered',
              2 => 'processed',
              3 => 'delivered',
              ),
              'default' => 'preordered',
              'notnull' => '1',
              'length' => '',
             ),
             'created_at' =>
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' =>
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' =>
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        //$this->removeColumn('mm_s_orders', 'delivery_price');
        //$this->removeColumn('mm_s_orders', 'status');
    }

    public function down()
    {
        $this->dropTable('mm_s_company_orders');
        $this->addColumn('mm_s_orders', 'delivery_price', 'integer', '8', array(
             'notnull' => '1',
             ));
        $this->addColumn('mm_s_orders', 'status', 'enum', '', array(
             'values' =>
             array(
              0 => 'preordered',
              1 => 'ordered',
              2 => 'processed',
              3 => 'delivered',
             ),
             'default' => 'preordered',
             'notnull' => '1',
             ));
    }
}