<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version42 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('mm_s_companies_orders', 'mm_s_companies_orders_order_id_mm_s_orders_id', array(
             'name' => 'mm_s_companies_orders_order_id_mm_s_orders_id',
             'local' => 'order_id',
             'foreign' => 'id',
             'foreignTable' => 'mm_s_orders',
             ));
        $this->addIndex('mm_s_companies_orders', 'mm_s_companies_orders_order_id', array(
             'fields' => 
             array(
              0 => 'order_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('mm_s_companies_orders', 'mm_s_companies_orders_order_id_mm_s_orders_id');
        $this->removeIndex('mm_s_companies_orders', 'mm_s_companies_orders_order_id', array(
             'fields' => 
             array(
              0 => 'order_id',
             ),
             ));
    }
}