generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sProperty
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          s_property
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:
        class: BackendsPropertyFormFilter
      form:
        class: BackendsPropertyForm
      edit:    ~
      new:     ~
